# config/packages/security.yaml

security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: auto

    role_hierarchy:
        #ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        #Indique la hiérarchie des rôles.
        #Rôle repris par défaut. Ici ROLE_ADMIN a les mêmes droits que ROLE_USER


    providers:
        database_users:
            entity: { class: App\Entity\Utilisateur, property: login }
        # used to reload user from session & other features (e.g. switch_user)



    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            logout:
                path: security_logout
            guard:
                authenticators:
                    - App\Security\FormLoginAuthenticator


    access_control:
        - { path: ^/pageaccueil, roles: [ROLE_USER,ROLE_ADMIN] }
        - { path: ^/abonnementAdmin, roles: ROLE_ADMIN }
        - { path: ^/abonnementUser, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/role/utilisateur/*, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/utilisateur/*, roles: [ROLE_ADMIN] }


